name: galaxy_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3+1
  flutter_staggered_grid_view: ^0.3.0
  flare_flutter: any
  flutter_custom_clippers: 1.1.0
  intl: ^0.16.1
  flutter_masked_text: ^0.8.0
  flutter_material_color_picker: ^1.0.5
  collection: any
  flutter_speed_dial: ^1.2.5
  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/svg/galaxy.svg
  - assets/svg/orbit.svg
  - assets/svg/moon2.svg
  - assets/svg/uranus.svg
  - assets/svg/star.svg
  - assets/svg/ventoso.svg
  - assets/svg/peso.svg
  - assets/svg/largura.svg
  - assets/svg/tamanho.svg
  - assets/svg/star4.svg
  - assets/svg/star3.svg
  - assets/svg/stars.svg
  - assets/svg/blackhole.svg
  - assets/animations/pinkPlanet.flr
  - assets/animations/pinkPlanetBig.flr
  - assets/animations/bluePlanet.flr
  - assets/animations/orangePlanet.flr
  - assets/animations/greenPlanet.flr
  - assets/animations/yellowPlanet.flr
  - assets/animations/greyPlanet.flr
  - assets/animations/pinkGalaxy.flr
  - assets/animations/blueGalaxy.flr
  - assets/animations/greenGalaxy.flr
  - assets/animations/yellowGalaxy.flr
  - assets/animations/orangeGalaxy.flr
  - assets/animations/greyGalaxy.flr
  - assets/animations/pinkSystem.flr
  - assets/animations/blueSystem.flr
  - assets/animations/orangeSystem.flr
  - assets/animations/yellowSystem.flr
  - assets/animations/greenSystem.flr
  - assets/animations/greySystem.flr
  - assets/animations/pinkHole.flr
  - assets/animations/blueHole.flr
  - assets/animations/yellowHole.flr
  - assets/animations/greenHole.flr
  - assets/animations/greyHole.flr
  - assets/animations/pinkSatelite.flr
  - assets/animations/blueSatelite.flr
  - assets/animations/greenSatelite.flr
  - assets/animations/yellowSatelite.flr
  - assets/animations/orangeSatelite.flr
  - assets/animations/greySatelite.flr
  - assets/animations/abStar.flr
  - assets/animations/avStar.flr
  - assets/animations/gaStar.flr
  - assets/animations/gvStar.flr
  - assets/animations/ebStar.flr
  - assets/animations/bnStar.flr
  - assets/animations/plOrbita.flr
  - assets/animations/slOrbita.flr
  - assets/animations/splOrbita.flr
  - assets/animations/spOrbita.flr
  - assets/icon/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages